.pragma library

var TITLE_BAR_HEIGHT = 122

var DIVIDER_DARK = "#515151"
var DIVIDER_LIGHT = "#d8d8d8"

var PROGRESS_BAR_BACKGROUND_DARK = "#3d3d3d"
var PROGRESS_BAR_BACKGROUND_LIGHT = "#d3d3d3"

var TEXT_COLOR_LIGHT = "#505050"
var TEXT_COLOR_DARK = "#f3f3f3"

var SECONDARY_TEXT_COLOR_LIGHT = "#636363"
var SECONDARY_TEXT_COLOR_DARK = "#d1d1d1"

var TITLE_TEXT_COLOR_LIGHT = "#505050"
var TITLE_TEXT_COLOR_DARK = "#e9e9e9"

var MENU_TITLE_BACKGROUND_COLOR_LIGHT = "#e9e9e9"
var MENU_TITLE_BACKGROUND_COLOR_DARK = "#222222"

var MENU_BACKGROUND_COLOR_LIGHT = "#fafafa"
var MENU_BACKGROUND_COLOR_DARK = "#333333"

var MENU_ITEM_HIGHLIGHT_LIGHT = "#222222"
var MENU_ITEM_HIGHLIGHT_DARK = "#e9e9e9"
