.pragma library

var TITLE_BAR_HEIGHT = 182

var DIVIDER_LIGHT = "#d8d8d8"
var DIVIDER_DARK = "#515151"

var TITLE_BAR_HIGHLIGHTER_LIGHT = "#d4d4d4"
var TITLE_BAR_HIGHLIGHTER_DARK = "#373737"

var TITLE_TEXT_COLOR_LIGHT = "#505050"
var TITLE_TEXT_COLOR_DARK = "#e9e9e9"

var PROGRESS_BAR_BACKGROUND_LIGHT = "#d3d3d3"
var PROGRESS_BAR_BACKGROUND_DARK = "#3d3d3d"

var TEXT_COLOR_LIGHT = "#505050"
var TEXT_COLOR_DARK = "#f3f3f3"

var TEXT_SECONDARY_COLOR_LIGHT = "#636363"
var TEXT_SECONDARY_COLOR_DARK = "#d1d1d1"

var MENU_TITLE_BACKGROUND_COLOR_LIGHT = "#bdc3c7"
var MENU_TITLE_BACKGROUND_COLOR_DARK = "#121212"

var MENU_BACKGROUND_COLOR_LIGHT = "#ecf0f1"
var MENU_BACKGROUND_COLOR_DARK = "#222222"

var LIST_DELEGATE_BACKGROUND_LIGHT = "#fafafa"
var LIST_DELEGATE_BACKGROUND_DARK = "#222222"

var LIST_DELEGATE_BACKGROUND_PRESSED_LIGHT = "#d8d8d8"
var LIST_DELEGATE_BACKGROUND_PRESSED_DARK = "#575757"

var MENU_ITEM_HIGHLIGHT_LIGHT = "#222222"
var MENU_ITEM_HIGHLIGHT_DARK = "#e9e9e9"
